CREATE TABLE author
(
    id         integer primary key generated by default as identity,
    last_name  text,
    first_name text
);

CREATE TABLE book
(
    id             integer primary key generated by default as identity,
    title          text,
    description    text,
    published_year integer,
    author_id      integer null references author (id)
);